feat: add lesson request validator
Orion-Constellation-Organization/Backend pull request #13
Opened 2024-11-04 17:31 UTC by RCAS2021

CHANGES 📝

Add lesson request validator
Update lesson request controller

Add lesson request repository

CARDS 📚

[Lesson Request Validations](https://trello.com/c/Mrz0pXRD/168-ocback-criar-validações-de-formulário-de-aula?filter=[oc])

NOTE 📝
Branch "feature/lesson-validator" -> "develop"

DETAILS 📝
Successfull registration:

![{15CCE2E5-5EFD-42BD-9442-6EF2EBB8B9A9}](https://github.com/user-attachments/assets/6dadbe22-05ba-4829-ad4a-b20b5a9c9fdf)

![{6CDD9DCA-0917-4C4F-B1C2-060EEE5D38EA}](https://github.com/user-attachments/assets/48ab95f6-2a85-4f2e-aec7-962de50c4950)

Registration errors:

Empty fields:
![{AAE62539-41F9-427A-8BF4-52E238B4D63C}](https://github.com/user-attachments/assets/e7eb7fb9-7936-4373-bfec-8ea4a9896cfd)

![{C96E3F2B-1882-490A-AC74-E71A5EC1F28A}](https://github.com/user-attachments/assets/81ee800f-32e4-421d-870e-0432abd1c6b2)

Reason not listed:
![{19798177-2799-456F-875A-E514263AED40}](https://github.com/user-attachments/assets/0e1d1bab-3d40-4684-a298-f90f0bf49d2b)

![{337E5F82-7AEA-41BF-A46C-CA6F25E4DB28}](https://github.com/user-attachments/assets/1ffc45cd-192b-4f1c-a120-a405caf5c081)

Wrong date format:
![{60F77947-3649-4E88-BBC5-EA4118C896C3}](https://github.com/user-attachments/assets/bdb42a80-64f6-4a69-9fe9-07b361ca4468)

![{10ECD796-12A2-4EE6-ABA3-7A0A6B48BE0A}](https://github.com/user-attachments/assets/12d39031-f70d-4a29-96b5-c567551fffbc)

Subject doesn't exist:
![{CA59C052-A2B8-4A50-8D83-BEA86FF6F001}](https://github.com/user-attachments/assets/4f67f5d3-cb1f-40b4-879e-c4a60fcbb62a)

![{43479DF7-36C3-4E3C-BCBB-AD6D7749F053}](https://github.com/user-attachments/assets/4e9ac5f1-a464-4350-bada-d336b5708f6e)

Student doesn't exist:
![{8825A47B-852B-4ADE-9EEF-1812FC98267A}](https://github.com/user-attachments/assets/013cc7c4-2af0-4fc3-8cf0-69ed461d22a1)

![{ACF2B0AF-ADB6-44C1-9AAA-BD8BC979E10E}](https://github.com/user-attachments/assets/972ce2e1-db23-4bc3-a12e-42440d237c45)

Get all lesson requests:
![{B2BDD962-8224-4D7A-8B97-2D725B365D57}](https://github.com/user-attachments/assets/be290158-4f8b-4015-b4a0-4dddabc87d70)

Swagger documentation:
![{5FAFDADD-82B7-4C95-8F15-2D31667ABD2D}](https://github.com/user-attachments/assets/f2938ead-f5bc-4bab-b102-1e51178ed003)
![{A9AE57D5-CC2F-4463-A389-41510459DC1C}](https://github.com/user-attachments/assets/c9febd6d-6e72-49ce-82c2-76f7c0196d58)

2024-11-05 10:44 UTC, G4brielSilva requested changes

2024-11-05 10:44 UTC, G4brielSilva commented on src/controller/LessonRequestController.ts
>    async create(req: Request, res: Response) {
a documentação do swagger não deveria estar acima do método create?

2024-11-05 10:44 UTC, G4brielSilva commented on src/entity/LessonRequest.ts
> +    default: StatusName.PENDENTE
É um padrão nomear enums como EnumStatusName

2024-11-05 10:44 UTC, G4brielSilva commented on src/validator/LessonRequestValidator.ts
> +            const [day, month, yearTime] = date.split('/');
Porque você não acorda com o front para fazer o envio da data já sanitizada pra você

2024-11-05 10:44 UTC, G4brielSilva commented
Fora identificado conflito para o merge

2024-11-06 14:51 UTC, G4brielSilva commented
Resolva os conflitos de merge primeiro

2024-11-08 09:40 UTC, G4brielSilva commented
Mais um conflito :)

2024-11-12 22:48 UTC, RCAS2021 commented on src/controller/LessonRequestController.ts
>    async create(req: Request, res: Response) {
feito.

2024-11-12 23:15 UTC, RCAS2021 commented on src/validator/LessonRequestValidator.ts
> +            const [day, month, yearTime] = date.split('/');
Conversei com o front e combinamos de manter, já que as datas em outras partes do código também estão sendo sanitizadas pelo back.

2024-11-15 14:16 UTC, G4brielSilva approved these changes

2024-11-15 14:28 UTC, merged