Consertando bug do banco de dados dentro do docker compose
Orion-Constellation-Organization/Backend pull request #2
Opened 2024-10-09 21:50 UTC by isaacbatista26

## Descrição

Durante algumas análises, foi identificado que o comando `docker compose up` gerava um erro de conexão entre os containers da API e do banco de dados. O problema ocorria porque o container da API tentava se conectar ao MySQL antes que este estivesse pronto para aceitar conexões. Este era o erro: 

  ![Erro de conexão](https://github.com/user-attachments/assets/22abfeed-1981-422b-b360-645988c45acc)

Anteriormente, para contornar essa questão, era necessário executar o comando duas vezes. Este PR resolve o problema adicionando uma verificação de saúde no container do MySQL. Agora, o container da API só é iniciado após o MySQL estar totalmente funcional e pronto para conexões.

Com essa modificação, agora o comando `docker compose up` inicializa corretamente todos os serviços em uma única execução:
  
  ![Execução bem-sucedida](https://github.com/user-attachments/assets/bde428e7-1f4f-4f38-8e2b-ebc692265e09)

2024-10-10 01:22 UTC, G4brielSilva requested changes

2024-10-10 01:22 UTC, G4brielSilva commented on docker-compose.yml
> +      orion-constellation-mysql:
Só um:
``` yml
    depends_on:
      - orion-constellation-mysql
```
não resolve?

2024-10-10 01:34 UTC, isaacbatista26 commented on docker-compose.yml
> +      orion-constellation-mysql:
eu tentei, mas não deu certo

2024-10-11 11:20 UTC, G4brielSilva approved these changes

2024-10-11 11:20 UTC, merged