feat: create get student confirmed lessons route and get student lessons by status
Orion-Constellation-Organization/Backend pull request #24
Opened 2024-11-19 22:44 UTC by RCAS2021

CHANGES 📝

- Add get student confirmed lesson requests route
- Add getStudentPendingLessons, getStudentConfirmedLessons and getStudentLessonsByStatus in student controller
- Update findPendingLessonByStudentId to findStudentLessonsByStatus to find lessons based on status in student repository
- Update getPendingLessonByStudentId to getStudentLessonsByStatus to get lessons based on status in student service
- Implement lesson request formatting using formatter function

CARDS 📚

[Lesson Request](https://trello.com/c/gRAwxd2p/36-get-aulas-confirmadas-aluno)

NOTE 📝

Branch "feature/student-confirmed-lessons" -> "feature/update-student-lesson"

DETAILS 📝
Get confirmed student lessons:
![{9B59B3EE-EE3A-423E-B5F1-2B2DEAAFA172}](https://github.com/user-attachments/assets/f5e9a9ce-caa9-4e1a-8c10-ad823a7e9a04)

Get pending student lessons:
![{5A1D9B82-AD79-4867-8F01-C3D38E719D8A}](https://github.com/user-attachments/assets/4d1bcf00-8365-494f-8788-425bc249a70f)

2024-11-20 02:32 UTC, G4brielSilva requested changes

2024-11-20 02:32 UTC, G4brielSilva commented on src/routes.ts
> +  '/api/get/student-confirmed-lessons/:id',
Faz sentido ter get na rota sendo que o método já é get?

2024-11-22 21:50 UTC, G4brielSilva requested changes

2024-11-22 21:50 UTC, G4brielSilva commented on src/routes.ts
> +  '/api/get/tutor/:id',
mais rotas get com get no path, corrija

2024-11-22 21:50 UTC, G4brielSilva commented on src/routes.ts
>    '/api/get/student-pending/:id',
essa também

2024-11-27 01:32 UTC, samuelcamilocosta commented
PR fechado por não cumprir os requisitos do gitflow e por estar desatualizado, orientei o Rafael com o caminho necessário para abrir o próximo PR para a develop

2024-11-27 01:32 UTC, closed without merging