feat: filtered lesson requests
Orion-Constellation-Organization/Backend pull request #28
Opened 2024-11-21 13:32 UTC by isaacbatista26

CHANGES 📝

Add getFilteredRequests function to Lesson Request:

- [x] Service
- [x] Repository
- [x] Route
- [x] Docs

CARDS 📝

[getFilteredRequests](https://trello.com/c/hXGhv2Kc)

2024-11-22 10:53 UTC, G4brielSilva requested changes
Resolver conflitos de merge

2024-11-22 21:48 UTC, G4brielSilva requested changes

2024-11-22 21:48 UTC, G4brielSilva commented on src/routes.ts
> +  '/api/get/lessonrequest/filtered/:id',
faz sentido a rota get ter get no nome da rota?

2024-11-25 23:46 UTC, samuelcamilocosta commented on src/repository/LessonRequestRepository.ts
> +    return await repository.find({
O uso do await com o return é desnecessário. Pode removê-lo aqui.
Em termos de execução seria igual um pleonasmo de tipo "retorne a resposta da função" - "retorne e aguarde a resposta da função". Como ele deve retornar a resposta, ele já entende que deve aguardar.

Vou inclusive deixar o link de uma regra no eslint que podemos adicionar para evitar que esquecermos disso

https://eslint.org/docs/latest/rules/no-return-await

2024-11-25 23:47 UTC, samuelcamilocosta commented on src/service/LessonRequestService.ts
> +  static async getFilteredRequests(tutorId) {
faltou tipar o retorno da função aqui

2024-11-25 23:47 UTC, samuelcamilocosta commented on src/repository/LessonRequestRepository.ts
> +  ) {
faltou tipar o retorno da função

2024-11-27 23:37 UTC, samuelcamilocosta commented on src/service/LessonRequestService.ts
> +      throw new AppError(EnumErrorMessages.ANY_LESSON_REQUEST_FOUND, 404);
Se lesson request for um array vazio, ele não é status 404 de erro. Seria status 200 com retorno de array [] vazio.
Status 404 seria caso batesse em uma rota inexistente por exemplo.
Afinal uma listagem de dados pode ser vazia e isso não necessariamente representaria um erro.
Status 404 representa um erro. É bom se atentar a isso

2024-11-27 23:37 UTC, samuelcamilocosta commented on src/repository/LessonRequestRepository.ts
> +  static async getAllLessonRequests(
como agora o endpoint terá paginação, getAllLessonRequests não se encaixa tão bem, já que não trará todas as LessonRequests de uma vez, mas sim a listagem de LessonRequests, já que possui paginação, etc.
Sugiro alterar para ListLessonRequests

2024-11-28 00:45 UTC, samuelcamilocosta approved these changes

2024-11-29 14:07 UTC, samuelcamilocosta requested changes

2024-11-29 14:07 UTC, samuelcamilocosta commented on src/repository/LessonRequestRepository.ts
> +import { EnumStatusName } from '../enum/EnumStatusName';
remover variável não utilizada

2024-11-29 14:07 UTC, samuelcamilocosta commented on src/repository/LessonRequestRepository.ts
> +import { Subject } from '../entity/Subject';
remover variável não utilizada

2024-11-29 14:07 UTC, samuelcamilocosta commented on src/repository/LessonRequestRepository.ts
> +import { EducationLevel } from '../entity/EducationLevel';
remover variável não utilizada

2024-11-29 14:07 UTC, samuelcamilocosta commented on src/repository/LessonRequestRepository.ts
> +import { In } from 'typeorm';
remover variável não utilizada

2024-11-29 14:07 UTC, samuelcamilocosta commented on src/service/LessonRequestService.ts
> +    const lessonRequests = await LessonRequestRepository.getFilteredRequests(
o código está falhando, pois se a função estava esperando 5 argumentos e recebeu 6, estourará erro, dar uma revisada aqui

2024-11-29 14:07 UTC, samuelcamilocosta commented on src/validator/LessonRequestValidator.ts
> +  static getLessonRequests() {
adicionar a tipagem do retorno da função

2024-11-29 14:07 UTC, samuelcamilocosta commented on src/service/LessonRequestService.ts
>    static async getLessonRequestById(id: number) {
adicionar tipagem de retorno da função

2024-11-29 18:06 UTC, samuelcamilocosta approved these changes

2024-11-29 19:28 UTC, G4brielSilva approved these changes

2024-11-29 19:28 UTC, merged