feat: create get student confirmed lessons route and function
Orion-Constellation-Organization/Backend pull request #30
Opened 2024-11-22 17:32 UTC by RCAS2021

CHANGES 📝

- Add get student confirmed lessons route
- Add get student confirmed lessons functions

CARDS 📚

[Lesson Request](https://trello.com/c/aSlOYc53/37-get-aulas-confirmadas-aluno)

NOTE 📝

Branch "feature/get-confirmed-lessons" -> "feature/update-lesson-status-accepted"

DETAILS 📝
Get confirmed student lessons:
![{A7F17667-751C-4A5E-BBFC-0234EEE88AB4}](https://github.com/user-attachments/assets/212d7249-d53b-43c1-81f0-c358d3be5a88)

2024-11-22 21:52 UTC, G4brielSilva requested changes

2024-11-22 21:52 UTC, G4brielSilva commented on src/routes.ts
> +  '/api/get/student-accepted-lessons/:id',
path incorreto

2024-11-22 21:53 UTC, G4brielSilva commented
resolver conflitos

2024-11-25 23:49 UTC, samuelcamilocosta approved these changes

2024-11-27 00:56 UTC, merged