feat: add tutor validator + tutor post route + tutor controller
Orion-Constellation-Organization/Backend pull request #5
Opened 2024-10-15 02:03 UTC by RCAS2021

CHANGES 📝

Adding tutor validation, tutor route and tutor controllers. 
Branch created from branch feature/create-entities.

CARDS 📚

[Tutor | Validator](https://trello.com/c/Dd5pC6dx/48-oc-back-adicionar-autenticação-de-cadastro-de-tutor)

2024-10-15 20:46 UTC, G4brielSilva requested changes

2024-10-15 20:46 UTC, G4brielSilva commented on package.json
> +    "bcrypt": "^5.1.1",
É interessante fixar a versão do pacote

2024-10-15 20:46 UTC, G4brielSilva commented on package.json
> +    "cpf-cnpj-validator": "^1.0.3",
Realmente é necessário um pacote para validar cpf e cnpj?

2024-10-15 20:46 UTC, G4brielSilva commented on src/controller/TutorController.ts
> +    console.log('Received request to save tutor:', req.body);
remover console.log

2024-10-15 20:46 UTC, G4brielSilva commented on src/controller/TutorController.ts
> +      console.log('Found education levels:', foundEducationLevels);
Remover console.log

2024-10-15 20:46 UTC, G4brielSilva commented on src/entity/Student.ts
> +  @Column({ type: 'varchar', length: 10, nullable: false })
Não seria melhor usar o tipo DATETIME para o dado de dia?

2024-10-15 20:46 UTC, G4brielSilva commented on src/entity/Tutor.ts
> +  @Column({ type: 'varchar', length: 10, nullable: false })
Faz sentido um dado que representa um dia ser representado com varchar ao invés de datetime ou date?

2024-10-15 20:46 UTC, G4brielSilva commented on src/validator/TutorValidator.ts
> +        .withMessage('CPF deve ser uma string.')
O usuário que preenche o formulário sabe o que é uma string? CPF inválido não é um erro mais consistente?

2024-10-15 20:46 UTC, G4brielSilva commented on src/validator/TutorValidator.ts
> +        .withMessage('Faixas de ensino devem ser uma lista de IDs.')
O parâmetro é educationLevel, e você está abordando como Faixas de ensino? Não há muita consistência

2024-10-15 21:28 UTC, RCAS2021 commented on package.json
> +    "cpf-cnpj-validator": "^1.0.3",
Eu poderia criar uma função, mas achei mais completo utilizando o pacote, já que ele já tem uma função para checar se o cpf é válido de acordo com as regras oficiais.

2024-10-15 21:31 UTC, RCAS2021 commented on src/entity/Student.ts
> +  @Column({ type: 'varchar', length: 10, nullable: false })
Essa parte das entidades, ficou de ser mudada na branch feature/create-entities. Como criei minha branch a partir dela, não fiz a alteração.

2024-10-18 00:07 UTC, G4brielSilva approved these changes

2024-10-18 00:07 UTC, merged