feat: New endpoints for Student, Tutor and Education Level
Orion-Constellation-Organization/Backend pull request #7
Opened 2024-10-17 01:55 UTC by isaacbatista26

CHANGES 📝

- Add 'POST' and 'GET' method to Student
- Add 'GET' method to Tutor
- Add 'POST' and 'GET' method to Education Level

CARDS📝

[Student Register](https://trello.com/c/fyEFXAGD/69-oc-back-criar-endpoint-de-cadastro-de-aluno)

NOTE 📝
Branch "feature/student-register" -> "fix/tutor-register-api"

2024-10-18 00:18 UTC, G4brielSilva requested changes

2024-10-18 00:18 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +    // const { hashedPassword, salt } = password;
remover código comentado

2024-10-18 00:18 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +    const salt = 'salt-exemple';
Usar um salt fixo tira parte do sentido de utilizar um salt

2024-10-18 00:18 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +    const salt = 'salt-exemple';
Usar um salt fixo tira parte do sentido de utilizar um salt

2024-10-18 00:18 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +      console.log('Found education levels:', foundEducationLevels);
remover console.log

2024-10-18 00:18 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +      return res.status(500).json({ message: 'Internal Server Error' });
Em certas partes do seu código você usa erros em português, outras usa erros em inglês. Escolha um padrão (preferencialmente inglês) e siga para todo o projeto

2024-10-18 00:40 UTC, isaacbatista26 commented on src/controller/StudentController.ts
> +    const salt = 'salt-exemple';
O salt foi declarado dessa forma porque a entidade Tutor, que estende a entidade User, exige a passagem de um salt:
![image](https://github.com/user-attachments/assets/b3e16b6f-6b12-4929-988f-665f1dd4d029)
Como este card não foca na lógica de validação, usei um salt de exemplo apenas para permitir testes da API via Postman e garantir que seja possível salvar usuários no banco de dados.

2024-10-24 01:01 UTC, G4brielSilva approved these changes

2024-10-24 01:01 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +    const salt = 'salt-exemple';
Sim, mas o salt ta fixo, você pode gerar um salt

2024-10-24 01:02 UTC, merged