feat: add student validator + common validations
Orion-Constellation-Organization/Backend pull request #8
Opened 2024-10-17 19:58 UTC by RCAS2021

CHANGES 📝

1. Add student validator
2. Add student validator to student post route
3. Fix student controller
4. Create common validations
5. Implement common validations in student and tutor validators

CARDS 📚

[Student | Validator](https://trello.com/c/WVU1YtVV/76-oc-back-adicionar-validação-de-cadastro-de-aluno)

NOTE 📝
Branch "feature/student-validator" -> "feature/student-register"

2024-10-18 00:25 UTC, G4brielSilva requested changes

2024-10-18 00:25 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +   *                   type: string
Porque você retornaria o salt no response?

2024-10-18 00:25 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +    const { hashedPassword, salt } = password;
Não ficou claro aqui, como que o parâmetro descrito no swagger como string é desestruturado em hashedPassword e salt, tem algum middleware ou algo assim processando isso e eu não vi?

2024-10-18 00:25 UTC, G4brielSilva commented on src/controller/StudentController.ts
>          where: { educationId: educationLevel }
Se esse valor for pareado com id, talvez um nome melhor seria educationLevelId

2024-10-18 00:25 UTC, G4brielSilva commented on src/validator/CommonValidations.ts
> +      .withMessage('Nome de usuário inválido.')
Novamente erros em Português, com outras partes do código em inglês, padronize :+1:

2024-10-18 00:32 UTC, RCAS2021 commented on src/controller/StudentController.ts
> +    const { hashedPassword, salt } = password;
No common validations, com a sanitização da senha do express validator, transforma a senha, pega o salt e faz o hash com o bcrypt e retorna a senha com o hash e o salt separados, pra ser salvo no bd separado tbm.

2024-10-19 16:27 UTC, G4brielSilva commented on src/controller/StudentController.ts
> +   *                   type: string
Você removeu apenas o swagger ou ta prevenindo o retorno do salt

2024-10-19 16:28 UTC, RCAS2021 commented on src/controller/StudentController.ts
> +   *                   type: string
prevenindo

2024-10-19 16:28 UTC, RCAS2021 commented on src/controller/StudentController.ts
> +   *                   type: string
inclusive preveni o retorno da senha com hash tbm

2024-10-22 01:25 UTC, G4brielSilva requested changes

2024-10-22 01:25 UTC, G4brielSilva commented on src/controller/TutorController.ts
>          where: { educationId: educationLevel }
Vale trocar os nomes em outros locais também

2024-10-27 22:36 UTC, G4brielSilva requested changes

2024-10-27 22:36 UTC, G4brielSilva commented on src/controller/TutorController.ts
> +        where: { educationId: In(educationLevelId) }
Considerando que o valor é um array educationLevelIds é preferível ao singular do mesmo

2024-10-28 22:20 UTC, G4brielSilva approved these changes

2024-10-28 22:20 UTC, G4brielSilva approved these changes

2024-10-28 22:20 UTC, G4brielSilva approved these changes

2024-10-29 11:15 UTC, G4brielSilva approved these changes

2024-10-29 11:15 UTC, merged